# Generated by Django 3.0.3 on 2020-05-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=300, null=True)),
                ('amount_people', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.CharField(blank=True, max_length=50)),
                ('student_ids', models.CharField(blank=True, max_length=13)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmutnbtrackapp.StudentID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmutnbtrackapp.Lab')),
            ],
        ),
    ]
