# Generated by Django 3.0.7 on 2020-06-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmutnbtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='amount',
            new_name='max_number_of_people',
        ),
    ]
