# Generated by Django 3.0.3 on 2020-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmutnbtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
        migrations.AddField(
            model_name='history',
            name='checkin',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='checkout',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
