# Generated by Django 3.0.6 on 2020-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmutnbtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='studentID',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
