# Generated by Django 3.0.3 on 2020-06-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmutnbtrackapp', '0002_auto_20200605_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='check_in_status',
        ),
    ]
