# Generated by Django 3.0.6 on 2020-05-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmutnbtrackapp', '0002_auto_20200530_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentid',
            old_name='studentID',
            new_name='student_id',
        ),
    ]
